title: Textual Libraries
description: > # this means to ignore newlines until "baseurl:"
  A collection of libraries and plugins for the Textual framework.
permalink: ':title/'
baseurl: "/textual-libraries"   # the subpath of your site, e.g. /blog
url: "http://edward-jazzhands.github.io" 

# Author Settings
author: Textual Libraries
author-img: logo.jpg
about-author: >
  A community-run collection of libraries, widgets, and plugins for the Textual framework,
  to help you make better Textual applications.

social-github: edward-jazzhands/textual-libraries

keywords: "textual,tui,libraries,plugins,framework,terminal,python"

# Disqus
# discus-identifier: 

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 30
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
